### ISSUE TITLE
ItemList component: click outside component does not close it

### ISSUE THREAD

**Issue by oandregal** [Automattic/happychat-client#131]
This is reproducible if you click outside the component but inside the iframe. Clicking outside the iframe would close the component.

**Comment by nosolosw** [comment]
My guess is that React is hooked to the `click` event of the host, but not the `click` event within the iframe.

**Comment by nosolosw** [comment]
This is the cause: at [this point](https://github.com/Automattic/happychat-client/blob/master/src/ui/components/select-dropdown/index.jsx#L107
), the component subscribes to the `click` event for the window object. happychat / react is scoped to the host so the global variables such as `document`, `window` represent the host document, not the iframe's - that's why it happens.

The ideal solution would be to bind the happychat UI / react to the iframe.
